llm:
  provider: openai
  config:
    model: 'gpt-4o-mini'
    temperature: 0.1
    max_tokens: 1000
    top_p: 1
    stream: false
    prompt: |
      Use the following pieces of context to answer the query at the end.
      If you don't know the answer, just say that you don't know, don't try to make up an answer.
      You must never give investment advice.
      If you simply don't know the answer, respond with "I don't know."
      Write a concise response to the query, including any relevant info you find in the docs.
      Use the docs if they are helpful, but if they aren't relevant, please exclude them when generating your response.
      You can use basic markdown in your response.

      $context

      Query: $query

      Helpful Answer:
embedder:
  provider: openai
  config:
    model: 'text-embedding-3-small'

